### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thewchan** [petereon/yakh#1]
Hi @petereon, I maintaining beaupy on Conda Forge (thanks for the great work by the way, I hope you don't mind me putting the package on Conda for wider audience), the new version now depends on yakh as well. Conda requires clear indication what license the pacakge is under and for the license to be packaged with the sdist. So I'm wondering if this can be done for yakh?

**Comment by petereon** [comment]
Hey @thewchan, thanks for maintaining it on Conda Forge! I am gonna add the license, release here, bump a version of `yakh` on `beaupy` and release there. Will that do it?

**Comment by thewchan** [comment]
yep, as long as the license is defined in either `pyproject.toml` or `setup.py` (or whatever) and the file itself is packaged in the sdist available on PyPI, we're good to go!

Also, let me know if you'd like the be co-maintainer on the conda side, work is minimal as new versions is automatically detected from PyPI, and there are automatic tests, and I usually only check to be sure depencies didn't change for minor/major version change and/or of tests fails. If you'd decide to let me have at it myself that's also totally fine!

**Comment by petereon** [comment]
I am okay to be included, though a bit afraid to make a mess as I have literally no experience with `conda` at all. Feel free to ping me on my [email](mailto:pvyboch1@gmail.com) if you'd prefer to use that channel for this conversation! I'll be closing this and releasing `beaupy` as soon as the CI passes.

**Comment by thewchan** [comment]
No worries, I can include you and I'll still be primary maintainer there. Thanks!
