### ISSUE TITLE
100% cpu use

### ISSUE THREAD

**Issue by amiguet** [petereon/yakh#4]
Hello,

This is a followup to a [beaupy issue](https://github.com/petereon/beaupy/issues/78).

I noticed that `get_key()` uses 100% of my cpu. To reproduce, use the code provided in the README:

```python
from yakh import get_key
from yakh.key import Keys

key = ''
while key not in ['q', Keys.ENTER]:
    key = get_key()
    if key.is_printable:
        print(key)
```

Python 3.11.5 on Linux, python-yakh==0.3.1 installed in a venv via pip as a dependency for beaupy.

**Comment by amiguet** [comment]
No idea if this is the right way of fixing this, but adding a tiny time.sleep in the outer loop of `__get_key()` in `_yakh.py` makes the cpu use drop to less than 1%:

```python
            while True:
                if ch_str != "":
                    break
                while True:
                    ch_stri = sys.stdin.read(1)
                    if ch_stri == "":
                        break
                    ch_str += ch_stri
                sleep(.02)
```

Just my 2¢...

**Comment by petereon** [comment]
@amiguet thank you very much for looking into this. 

I will investigate a little bit, as I'd like to avoid an explicit `sleep` because I am afraid it will mess with `stdin` stream, which I've found to be exceptionally brittle.

If no better option offers itself, I am going to go for this. If you are so inclined, feel free to open a pull request containing this change.

**Comment by amiguet** [comment]
Wow that was quick!

I didn't know about `select.select()`, but this is of course a much better solution than the `sleep()` workaround.

This works very well for me, many thanks! :-)

**Comment by petereon** [comment]
I only learned about it yesterday too. Curiously it popped out as a first result, despite the fact I've spent several hours researching how `stdin` can be interrogated to see if it has any contents when I was first implementing that.

Glad to be of help!
